$(call PKG_INIT_BIN, 4.0.4)
$(PKG)_SOURCE:=procps-ng-$($(PKG)_VERSION).tar.xz
$(PKG)_HASH:=22870d6feb2478adb617ce4f09a787addaf2d260c5a8aa7b17d889a962c5e42e
$(PKG)_SITE:=@SF/procps-ng/Production
### WEBSITE:=https://gitlab.com/procps-ng/procps
### MANPAGE:=https://linux.die.net/man/1/ps
### CHANGES:=https://gitlab.com/procps-ng/procps/-/tags
### CVSREPO:=https://gitlab.com/procps-ng/procps
### SUPPORT:=Ircama

# Define build and target paths for each binary
$(PKG)_PS_BUILD := $(PROCPS_FULL_DIR)/src/ps/pscommand
$(PKG)_PS_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/psfull

$(PKG)_TOP_BUILD := $(PROCPS_FULL_DIR)/src/top/top
$(PKG)_TOP_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/topfull

$(PKG)_FREE_BUILD := $(PROCPS_FULL_DIR)/src/free
$(PKG)_FREE_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/freefull

$(PKG)_UPTIME_BUILD := $(PROCPS_FULL_DIR)/src/uptime
$(PKG)_UPTIME_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/uptimefull

$(PKG)_VMSTAT_BUILD := $(PROCPS_FULL_DIR)/src/vmstat
$(PKG)_VMSTAT_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/vmstatfull

$(PKG)_W_BUILD := $(PROCPS_FULL_DIR)/src/w
$(PKG)_W_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/wfull

$(PKG)_PMAP_BUILD := $(PROCPS_FULL_DIR)/src/pmap
$(PKG)_PMAP_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/pmapfull

$(PKG)_PGREP_BUILD := $(PROCPS_FULL_DIR)/src/pgrep
$(PKG)_PGREP_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/pgrepfull

$(PKG)_PKILL_BUILD := $(PROCPS_FULL_DIR)/src/pkill
$(PKG)_PKILL_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/pkillfull

$(PKG)_PIDOF_BUILD := $(PROCPS_FULL_DIR)/src/pidof
$(PKG)_PIDOF_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/pidoffull

$(PKG)_PWDX_BUILD := $(PROCPS_FULL_DIR)/src/pwdx
$(PKG)_PWDX_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/pwdxfull

$(PKG)_SLABTOP_BUILD := $(PROCPS_FULL_DIR)/src/slabtop
$(PKG)_SLABTOP_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/slabtopfull

$(PKG)_TLOAD_BUILD := $(PROCPS_FULL_DIR)/src/tload
$(PKG)_TLOAD_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/tloadfull

$(PKG)_WATCH_BUILD := $(PROCPS_FULL_DIR)/src/watch
$(PKG)_WATCH_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/watchfull

$(PKG)_SKILL_BUILD := $(PROCPS_FULL_DIR)/src/skill
$(PKG)_SKILL_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/skillfull

$(PKG)_SNICE_BUILD := $(PROCPS_FULL_DIR)/src/snice
$(PKG)_SNICE_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/snicefull

$(PKG)_SYSCTL_BUILD := $(PROCPS_FULL_DIR)/src/sysctl
$(PKG)_SYSCTL_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/sysctlfull

$(PKG)_KILL_BUILD := $(PROCPS_FULL_DIR)/src/kill
$(PKG)_KILL_TARGET := $(PROCPS_FULL_DEST_DIR)/usr/bin/killfull

$(PKG)_CONFIGURE_PRE_CMDS += $(call PKG_PREVENT_RPATH_HARDCODING,./configure)

$(PKG)_CONFIGURE_OPTIONS += --enable-static
$(PKG)_CONFIGURE_OPTIONS += --disable-shared
$(PKG)_CONFIGURE_OPTIONS += --disable-nls
$(PKG)_CONFIGURE_OPTIONS += --enable-w-from
$(PKG)_CONFIGURE_OPTIONS += --enable-skill
$(PKG)_CONFIGURE_OPTIONS += --without-systemd
$(PKG)_CONFIGURE_OPTIONS += --without-elogind
$(PKG)_CONFIGURE_OPTIONS += ac_cv_func_malloc_0_nonnull=yes
$(PKG)_CONFIGURE_OPTIONS += ac_cv_func_realloc_0_nonnull=yes


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CONFIGURE)

# Build all binaries together
$(PROCPS_FULL_PS_BUILD) $(PROCPS_FULL_TOP_BUILD) $(PROCPS_FULL_FREE_BUILD) $(PROCPS_FULL_UPTIME_BUILD) $(PROCPS_FULL_VMSTAT_BUILD) $(PROCPS_FULL_W_BUILD) $(PROCPS_FULL_PMAP_BUILD) $(PROCPS_FULL_PGREP_BUILD) $(PROCPS_FULL_PKILL_BUILD) $(PROCPS_FULL_PIDOF_BUILD) $(PROCPS_FULL_PWDX_BUILD) $(PROCPS_FULL_SLABTOP_BUILD) $(PROCPS_FULL_TLOAD_BUILD) $(PROCPS_FULL_WATCH_BUILD) $(PROCPS_FULL_SKILL_BUILD) $(PROCPS_FULL_SNICE_BUILD) $(PROCPS_FULL_SYSCTL_BUILD) $(PROCPS_FULL_KILL_BUILD): $(PROCPS_FULL_DIR)/.configured
	$(SUBMAKE) -C $(PROCPS_FULL_DIR)

# Install each binary
$(PROCPS_FULL_PS_TARGET): $(PROCPS_FULL_PS_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_TOP_TARGET): $(PROCPS_FULL_TOP_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_FREE_TARGET): $(PROCPS_FULL_FREE_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_UPTIME_TARGET): $(PROCPS_FULL_UPTIME_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_VMSTAT_TARGET): $(PROCPS_FULL_VMSTAT_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_W_TARGET): $(PROCPS_FULL_W_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_PMAP_TARGET): $(PROCPS_FULL_PMAP_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_PGREP_TARGET): $(PROCPS_FULL_PGREP_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_PKILL_TARGET): $(PROCPS_FULL_PKILL_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_PIDOF_TARGET): $(PROCPS_FULL_PIDOF_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_PWDX_TARGET): $(PROCPS_FULL_PWDX_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_SLABTOP_TARGET): $(PROCPS_FULL_SLABTOP_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_TLOAD_TARGET): $(PROCPS_FULL_TLOAD_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_WATCH_TARGET): $(PROCPS_FULL_WATCH_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_SKILL_TARGET): $(PROCPS_FULL_SKILL_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_SNICE_TARGET): $(PROCPS_FULL_SNICE_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_SYSCTL_TARGET): $(PROCPS_FULL_SYSCTL_BUILD)
	$(INSTALL_BINARY_STRIP)

$(PROCPS_FULL_KILL_TARGET): $(PROCPS_FULL_KILL_BUILD)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_PS),$(PROCPS_FULL_PS_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_TOP),$(PROCPS_FULL_TOP_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_FREE),$(PROCPS_FULL_FREE_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_UPTIME),$(PROCPS_FULL_UPTIME_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_VMSTAT),$(PROCPS_FULL_VMSTAT_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_W),$(PROCPS_FULL_W_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_PMAP),$(PROCPS_FULL_PMAP_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_PGREP),$(PROCPS_FULL_PGREP_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_PKILL),$(PROCPS_FULL_PKILL_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_PIDOF),$(PROCPS_FULL_PIDOF_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_PWDX),$(PROCPS_FULL_PWDX_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_SLABTOP),$(PROCPS_FULL_SLABTOP_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_TLOAD),$(PROCPS_FULL_TLOAD_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_WATCH),$(PROCPS_FULL_WATCH_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_SKILL),$(PROCPS_FULL_SKILL_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_SNICE),$(PROCPS_FULL_SNICE_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_SYSCTL),$(PROCPS_FULL_SYSCTL_TARGET)) \
	$(if $(FREETZ_PACKAGE_PROCPS_FULL_KILL),$(PROCPS_FULL_KILL_TARGET))


$(pkg)-clean:
	-$(SUBMAKE) -C $(PROCPS_FULL_DIR) clean
	$(RM) $(PROCPS_FULL_DIR)/.configured

$(pkg)-uninstall:
	$(RM) $(PROCPS_FULL_PS_TARGET)
	$(RM) $(PROCPS_FULL_TOP_TARGET)
	$(RM) $(PROCPS_FULL_FREE_TARGET)
	$(RM) $(PROCPS_FULL_UPTIME_TARGET)
	$(RM) $(PROCPS_FULL_VMSTAT_TARGET)
	$(RM) $(PROCPS_FULL_W_TARGET)
	$(RM) $(PROCPS_FULL_PMAP_TARGET)
	$(RM) $(PROCPS_FULL_PGREP_TARGET)
	$(RM) $(PROCPS_FULL_PKILL_TARGET)
	$(RM) $(PROCPS_FULL_PIDOF_TARGET)
	$(RM) $(PROCPS_FULL_PWDX_TARGET)
	$(RM) $(PROCPS_FULL_SLABTOP_TARGET)
	$(RM) $(PROCPS_FULL_TLOAD_TARGET)
	$(RM) $(PROCPS_FULL_WATCH_TARGET)
	$(RM) $(PROCPS_FULL_SKILL_TARGET)
	$(RM) $(PROCPS_FULL_SNICE_TARGET)
	$(RM) $(PROCPS_FULL_SYSCTL_TARGET)
	$(RM) $(PROCPS_FULL_KILL_TARGET)

$(PKG_FINISH)
