#! /usr/bin/env bash
MYOWN="$(realpath $0)"
TOOLS="$(dirname $(dirname $MYOWN))"
MGC="$TOOLS/build/usr/share/misc/magic.mgc"

file="$TOOLS/build/usr/bin/file"
[ -x "$file" ] && exec "$file" -m $MGC "$@"

file="$(which -a 'file' | grep -v "^$MYOWN$" | head -n1)"
[ -x "$file" ] && exec "$file" -m $MGC "$@"

echo "Miserable failure, no file binary!" >&2
exit 1
