name: image_generate

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/image_generate.yml'
      - '.github/docker/generate/*'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/docker/*/*'
  schedule:
    - cron: '45 18 28 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}${{ github.event.pull_request.number && '-' }}${{ github.event.pull_request.number || '' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' && false || true }}


jobs:
  build:
    permissions:
      contents: read
      packages: write
      pull-requests: read
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch'

    steps:

      - name: checkout
        uses: actions/checkout@v6

      - name: prepare
        id: prepare
        run: |
          OWNER="freetz-ng"
          IMAGE="$(echo "${{ github.workflow }}" | sed 's/.*_//')"
          URI="ghcr.io/$OWNER/internal/$IMAGE"
          echo "uri=$URI" >> $GITHUB_OUTPUT
          echo "################################################################" && echo "URI=$uri"

      - name: login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.FREETZ_DLTOKEN }}
        if: github.repository == 'freetz-ng/freetz-ng' && github.event_name != 'pull_request'

      - name: docker
        uses: docker/build-push-action@v7
        with:
          context: .github/docker/${{ matrix.image }}
          tags: ${{ steps.prepare.outputs.uri }}:latest
          push: ${{ github.repository == 'freetz-ng/freetz-ng' && github.event_name != 'pull_request' }}


